console.log('%c Onix bot ØªÙ… Ø¹Ù…Ù„ Ø§Ù„Ù…ÙˆÙ‚Ø¹ Ø¨ÙˆØ§Ø³Ø·Ø© Ù…Ø¨Ø±Ù…Ø¬ÙŠÙ† ', 'background: #222; color: #a29bfe');
console.log('%c', 'background: #222; color: #fff');
console.log('%c Onix bot ÙØ±ÙŠÙ‚', 'background: #222; color: #fff');
console.log('%c Fireking ', 'background: #222; color: #a29bfe');
console.log('%c iUltRaX ', 'background: #222; color: #a29bfe');
console.log('%c .Ahmeeed ', 'background: #222; color: #a29bfe');
console.log('%c ,YouseeeF ', 'background: #222; color: #a29bfe');
console.log('%c E3SAR ', 'background: #222; color: #a29bfe');
console.log('%c M7MD ', 'background: #222; color: #a29bfe');
console.log('%c', 'background: #222; color: #FFC312');
console.log('%c Onix bot Ø¬Ù…ÙŠØ¹ Ø§Ù„Ø­Ù‚ÙˆÙ‚ Ù…Ø­ÙÙˆØ¸Ø© Ù„Ø¯ÙŠ Ù…Ø¨Ø±Ù…Ø¬ÙŠÙ†  ', 'background: #222; color: #fff');